name: ci-node-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['15', '16']
    steps:
      - name: Checkout dependencies
        uses: actions/checkout@v3
      - name: Setup Node dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
      # - name: Run Application
      #   run: npm start
